export type TQuestion = {
  id: number;
  text: string;
  type:
    | "multiple-choice" // Standard multiple-choice question with one correct answer
    | "true-false" // Standard true/false question
    | "short-answer" // Open-ended question where players type their answer
    | "fill-in-the-blank" // Question with a blank to fill in, e.g. "The capital of France is ___"
    | "matching" // Players match items from two lists, e.g. "Match the country with its capital"
    | "ordering" // Players arrange items in the correct order, e.g. "Arrange the historical events in chronological order"
    | "image-based" // Question that requires players to identify something in an image
    | "audio-based" // Question that requires players to identify something in an audio clip
    | "video-based" // Question that requires players to identify something in a video clip
    | "code-snippet" // Question that requires players to analyze a code snippet and answer a question about it
    | "drag-and-drop" // Question that requires players to drag and drop answers into the correct positions
    | "guess-the-number" // Question that requires players to guess a number within a certain range
    | "memorize-the-order" // Question that requires players to memorize the order of items and recall them
    | "reveal-in-order" // Question that requires players to reveal the answers in a specific order to solve a puzzle
    | "multiple-choice-shared-answers"; // Answer locked once selected, shared among multiple questions
  options?: string[]; // Only for multiple-choice questions
  leftOptions?: string[]; // For matching questions, the options on the left side
  rightOptions?: string[]; // For matching questions, the options on the right side
  src?: string; // For image-based, audio-based, and video-based questions, the source URL of the media
  correctAnswer: string | boolean; // String for multiple-choice, short-answer, and fill-in-the-blank, boolean for true-false
  points: number;
  doublePoints?: boolean; // If true, points for this question are doubled if answered correctly and reduce by double if answered incorrectly
  answeredBy?: {
    [playerId: number]: {
      answer: TQuestion["correctAnswer"];
      skipped: boolean;
    };
  };
};

export enum ECategory {
  GENERAL = "general",
  SCIENCE = "science",
  HISTORY = "history",
  ENTERTAINMENT = "entertainment",
  SPORTS = "sports",
  GEOGRAPHY = "geography",
  LITERATURE = "literature",
  TECHNOLOGY = "technology",
  ART = "art",
  MUSIC = "music",
  MOVIES = "movies",
  TV_SHOWS = "tv-shows",
  VIDEO_GAMES = "video-games",
  FOOD_AND_DRINK = "food-and-drink",
  ANIMALS = "animals",
  NATURE = "nature",
  SPACE = "space",
  MATH = "math",
  LANGUAGE = "language",
  MISCELLANEOUS = "miscellaneous",
  CODING = "coding",
}

export enum EStatus {
  DRAFT = "draft",
  PUBLISHED = "published",
  ARCHIVED = "archived",
}

export enum EDifficulty {
  EASY = "easy",
  MEDIUM = "medium",
  HARD = "hard",
  EXPERT = "expert",
}

export enum EGameMode {
  CLASSIC = "classic",
  TIMED = "timed",
  SURVIVAL = "survival",
}

export type TQuiz = {
  id: number;
  title: string;
  description: string;
  creatorId: number;
  status?: EStatus;
  category: ECategory;
  difficulty: EDifficulty;
  // Game modes:
  // - classic: standard quiz format with a fixed number of questions and no time limit
  // - timed: players have a limited amount of time to answer each question
  // - survival: players continue until they answer incorrectly, with a limited number of lives
  gameMode: EGameMode;
  settings: {
    timeLimitPerRound: number; // in seconds
    passingScorePercentage: number; // percentage required to pass
    shuffleQuestions: boolean;
    immediateResults: boolean;
    lives: number; // maximum attempts allowed
  };
  questions: TQuestion[];
  createdAt: string;
  updatedAt: string;
};

export const dbQuiz: TQuiz[] = [
  {
    id: 1,
    title: "General Knowledge Quiz",
    description: "Test your general knowledge with this fun quiz!",
    creatorId: 123,
    status: EStatus.PUBLISHED,
    category: ECategory.GENERAL,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 60,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "What is the capital of France?",
        type: "multiple-choice",
        options: ["Paris", "London", "Berlin", "Madrid"],
        correctAnswer: "Paris",
        points: 10,
        doublePoints: true,
      },
      {
        id: 2,
        text: "The Earth is flat.",
        type: "true-false",
        correctAnswer: false,
        points: 5,
      },
      {
        id: 3,
        text: "Who wrote 'To Kill a Mockingbird'?",
        type: "short-answer",
        correctAnswer: "Harper Lee",
        points: 15,
      },
      {
        id: 4,
        text: "The chemical symbol for water is ___.",
        type: "fill-in-the-blank",
        correctAnswer: "H2O",
        points: 10,
      },
      {
        id: 5,
        text: "Match the following countries with their capitals.",
        type: "matching",
        leftOptions: ["France", "Germany", "Spain", "Italy"],
        rightOptions: ["Paris", "Berlin", "Madrid", "Rome"],
        correctAnswer: "France - Paris, Germany - Berlin, Spain - Madrid, Italy - Rome",
        points: 20,
      },
      {
        id: 6,
        text: "Arrange the following historical events in chronological order.",
        type: "ordering",
        options: ["World War I", "American Revolution", "French Revolution", "World War II"],
        correctAnswer: "American Revolution, French Revolution, World War I, World War II",
        points: 20,
      },
      {
        id: 7,
        text: "Identify the object in the image.",
        type: "image-based",
        src: "https://cdn.britannica.com/89/187589-050-E8D5A657/Workers-Big-Ben-London.jpg",
        options: ["Eiffel Tower", "Statue of Liberty", "Big Ben", "Colosseum"],
        correctAnswer: "Eiffel Tower",
        points: 15,
      },
      {
        id: 8,
        text: "Listen to the audio and identify the song.",
        type: "audio-based",
        src: "https://freepik-tunes.s3.amazonaws.com/tracks/950f1cb8_Audio_People.mp3",
        options: ["Song A", "Song B", "Song C", "Song D"],
        correctAnswer: "Song A",
        points: 15,
      },
      {
        id: 9,
        text: "Watch the video and answer the question.",
        type: "video-based",
        options: ["Option 1", "Option 2", "Option 3", "Option 4"],
        correctAnswer: "Option 2",
        points: 15,
      },
      {
        id: 10,
        text: "What does the following code snippet output?",
        type: "code-snippet",
        options: ["Output A", "Output B", "Output C", "Output D"],
        correctAnswer: "Output C",
        points: 20,
      },
      {
        id: 11,
        text: "Drag and drop the correct answers into the boxes.",
        type: "drag-and-drop",
        options: ["Option A", "Option B", "Option C", "Option D"],
        correctAnswer: "Option A, Option C",
        points: 20,
      },
      {
        id: 12,
        text: "Guess the number between 1 and 100.",
        type: "guess-the-number",
        correctAnswer: "42",
        points: 25,
      },
      {
        id: 13,
        text: "Memorize the order of the following items and recall them.",
        type: "memorize-the-order",
        options: ["Item A", "Item B", "Item C", "Item D"],
        correctAnswer: "Item B, Item D, Item A, Item C",
        points: 20,
      },
      {
        id: 14,
        text: "Reveal the answers in the correct order to solve the puzzle.",
        type: "reveal-in-order",
        options: ["Answer A", "Answer B", "Answer C", "Answer D"],
        correctAnswer: "Answer C, Answer A, Answer D, Answer B",
        points: 20,
      },
      {
        id: 15,
        text: "Select the correct answer that is shared among multiple questions.",
        type: "multiple-choice-shared-answers",
        options: ["Shared Answer A", "Shared Answer B", "Shared Answer C", "Shared Answer D"],
        correctAnswer: "Shared Answer B",
        points: 15,
      },
    ],
    createdAt: "2024-01-01T12:00:00Z",
    updatedAt: "2024-01-02T12:00:00Z",
  },
  {
    id: 2,
    title: "Science Fundamentals",
    description: "Test your basic science knowledge with this beginner-friendly quiz!",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.SCIENCE,
    difficulty: EDifficulty.EASY,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 45,
      passingScorePercentage: 60,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 5,
    },
    questions: [
      {
        id: 1,
        text: "What planet is known as the Red Planet?",
        type: "multiple-choice",
        options: ["Mars", "Venus", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
        points: 10,
      },
      {
        id: 2,
        text: "Water boils at 100°C at sea level.",
        type: "true-false",
        correctAnswer: true,
        points: 5,
      },
      {
        id: 3,
        text: "The center of an atom is called the ___.",
        type: "fill-in-the-blank",
        correctAnswer: "nucleus",
        points: 10,
      },
      {
        id: 4,
        text: "How many bones are in the adult human body?",
        type: "multiple-choice",
        options: ["206", "208", "195", "212"],
        correctAnswer: "206",
        points: 15,
      },
    ],
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: 3,
    title: "World War II History",
    description: "Explore the key events and figures of World War II",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.HISTORY,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.TIMED,
    settings: {
      timeLimitPerRound: 30,
      passingScorePercentage: 70,
      shuffleQuestions: false,
      immediateResults: false,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "In what year did World War II begin?",
        type: "multiple-choice",
        options: ["1939", "1940", "1938", "1941"],
        correctAnswer: "1939",
        points: 10,
      },
      {
        id: 2,
        text: "Arrange these WWII events in chronological order.",
        type: "ordering",
        options: [
          "Pearl Harbor Attack",
          "D-Day Invasion",
          "Battle of Stalingrad",
          "Hiroshima Bombing",
        ],
        correctAnswer:
          "Pearl Harbor Attack, Battle of Stalingrad, D-Day Invasion, Hiroshima Bombing",
        points: 25,
        doublePoints: true,
      },
      {
        id: 3,
        text: "Who was the Prime Minister of Britain during most of WWII?",
        type: "short-answer",
        correctAnswer: "Winston Churchill",
        points: 15,
      },
      {
        id: 4,
        text: "The Battle of Midway was fought in the Pacific Ocean.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 5,
        text: "Match the code names with their operations.",
        type: "matching",
        leftOptions: [
          "Operation Overlord",
          "Operation Barbarossa",
          "Operation Market Garden",
          "Operation Torch",
        ],
        rightOptions: ["D-Day", "Invasion of USSR", "Netherlands", "North Africa"],
        correctAnswer:
          "Operation Overlord - D-Day, Operation Barbarossa - Invasion of USSR, Operation Market Garden - Netherlands, Operation Torch - North Africa",
        points: 30,
      },
    ],
    createdAt: "2024-02-01T14:20:00Z",
    updatedAt: "2024-02-05T09:15:00Z",
  },
  {
    id: 4,
    title: "Advanced JavaScript Concepts",
    description: "Challenge yourself with advanced JavaScript patterns and concepts",
    creatorId: 123,
    status: EStatus.DRAFT,
    category: ECategory.TECHNOLOGY,
    difficulty: EDifficulty.HARD,
    gameMode: EGameMode.SURVIVAL,
    settings: {
      timeLimitPerRound: 90,
      passingScorePercentage: 80,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What does the following code snippet output? console.log(typeof null);",
        type: "code-snippet",
        options: ["object", "null", "undefined", "error"],
        correctAnswer: "object",
        points: 20,
        doublePoints: true,
      },
      {
        id: 2,
        text: "Event delegation works by utilizing event bubbling.",
        type: "true-false",
        correctAnswer: true,
        points: 15,
      },
      {
        id: 3,
        text: "What keyword is used to create a constant reference in JavaScript?",
        type: "fill-in-the-blank",
        correctAnswer: "const",
        points: 10,
      },
    ],
    createdAt: "2024-02-10T16:45:00Z",
    updatedAt: "2024-02-10T16:45:00Z",
  },
  {
    id: 5,
    title: "Classic Movie Trivia",
    description: "How well do you know the greatest films of all time?",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.MOVIES,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 60,
      passingScorePercentage: 65,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 4,
    },
    questions: [
      {
        id: 1,
        text: "Which movie won the Academy Award for Best Picture in 1994?",
        type: "multiple-choice",
        options: ["Forrest Gump", "The Shawshank Redemption", "Pulp Fiction", "The Lion King"],
        correctAnswer: "Forrest Gump",
        points: 15,
      },
      {
        id: 2,
        text: "Identify the movie from this iconic scene.",
        type: "image-based",
        src: "https://www.rollingstone.com/wp-content/uploads/2020/08/goodfellasc.jpg?w=1581&h=1054&crop=1",
        options: ["The Godfather", "Scarface", "Goodfellas", "Casino"],
        correctAnswer: "The Godfather",
        points: 20,
      },
      {
        id: 3,
        text: "Match the movies with their directors.",
        type: "matching",
        leftOptions: ["Inception", "The Grand Budapest Hotel", "Parasite", "Get Out"],
        rightOptions: ["Christopher Nolan", "Wes Anderson", "Bong Joon-ho", "Jordan Peele"],
        correctAnswer:
          "Inception - Christopher Nolan, The Grand Budapest Hotel - Wes Anderson, Parasite - Bong Joon-ho, Get Out - Jordan Peele",
        points: 25,
      },
      {
        id: 4,
        text: "Steven Spielberg directed Jurassic Park.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 5,
        text: "Who played Jack Dawson in Titanic?",
        type: "short-answer",
        correctAnswer: "Leonardo DiCaprio",
        points: 15,
      },
    ],
    createdAt: "2024-02-20T11:00:00Z",
    updatedAt: "2024-02-20T11:00:00Z",
  },
  {
    id: 6,
    title: "Python Programming Mastery",
    description: "Expert-level Python programming challenges for seasoned developers",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.CODING,
    difficulty: EDifficulty.EXPERT,
    gameMode: EGameMode.SURVIVAL,
    settings: {
      timeLimitPerRound: 120,
      passingScorePercentage: 85,
      shuffleQuestions: false,
      immediateResults: false,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What does the following code output? print([i for i in range(5) if i % 2 == 0])",
        type: "code-snippet",
        options: ["[0, 2, 4]", "[1, 3]", "[0, 1, 2, 3, 4]", "[2, 4]"],
        correctAnswer: "[0, 2, 4]",
        points: 25,
        doublePoints: true,
      },
      {
        id: 2,
        text: "A decorator in Python is a function that takes another function and extends its behavior.",
        type: "true-false",
        correctAnswer: true,
        points: 20,
      },
      {
        id: 3,
        text: "Arrange these Python concepts from basic to advanced.",
        type: "ordering",
        options: ["Variables", "Functions", "Decorators", "Metaclasses"],
        correctAnswer: "Variables, Functions, Decorators, Metaclasses",
        points: 30,
      },
      {
        id: 4,
        text: "The ___ statement in Python is used to handle exceptions.",
        type: "fill-in-the-blank",
        correctAnswer: "try",
        points: 15,
      },
    ],
    createdAt: "2024-02-25T13:30:00Z",
    updatedAt: "2024-02-28T10:20:00Z",
  },
  {
    id: 7,
    title: "World Geography Basics",
    description: "Test your knowledge of countries, capitals, and continents",
    creatorId: 123,
    status: EStatus.ARCHIVED,
    category: ECategory.GEOGRAPHY,
    difficulty: EDifficulty.EASY,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 40,
      passingScorePercentage: 60,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 4,
    },
    questions: [
      {
        id: 1,
        text: "What is the largest continent by land area?",
        type: "multiple-choice",
        options: ["Asia", "Africa", "North America", "Europe"],
        correctAnswer: "Asia",
        points: 10,
      },
      {
        id: 2,
        text: "The Nile River is the longest river in the world.",
        type: "true-false",
        correctAnswer: true,
        points: 5,
      },
      {
        id: 3,
        text: "What is the capital of Australia?",
        type: "short-answer",
        correctAnswer: "Canberra",
        points: 15,
      },
      {
        id: 4,
        text: "Match the countries with their continents.",
        type: "matching",
        leftOptions: ["Brazil", "Egypt", "Japan", "Germany"],
        rightOptions: ["South America", "Africa", "Asia", "Europe"],
        correctAnswer: "Brazil - South America, Egypt - Africa, Japan - Asia, Germany - Europe",
        points: 20,
      },
    ],
    createdAt: "2023-12-15T09:00:00Z",
    updatedAt: "2024-01-10T14:30:00Z",
  },
  {
    id: 8,
    title: "Sports Legends Quiz",
    description: "How well do you know the greatest athletes and moments in sports history?",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.SPORTS,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.TIMED,
    settings: {
      timeLimitPerRound: 45,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "Which athlete has won the most Olympic gold medals?",
        type: "multiple-choice",
        options: ["Michael Phelps", "Usain Bolt", "Simone Biles", "Carl Lewis"],
        correctAnswer: "Michael Phelps",
        points: 15,
      },
      {
        id: 2,
        text: "The FIFA World Cup is held every four years.",
        type: "true-false",
        correctAnswer: true,
        points: 5,
      },
      {
        id: 3,
        text: "Arrange these sports events in the order they were first held.",
        type: "ordering",
        options: ["Modern Olympics", "FIFA World Cup", "Super Bowl", "NBA Finals"],
        correctAnswer: "Modern Olympics, FIFA World Cup, NBA Finals, Super Bowl",
        points: 25,
      },
      {
        id: 4,
        text: "Who is known as 'The GOAT' in basketball?",
        type: "short-answer",
        correctAnswer: "Michael Jordan",
        points: 15,
      },
      {
        id: 5,
        text: "Match the sport with its championship trophy.",
        type: "matching",
        leftOptions: ["NHL", "NFL", "NBA", "MLB"],
        rightOptions: [
          "Stanley Cup",
          "Lombardi Trophy",
          "Larry O'Brien Trophy",
          "Commissioner's Trophy",
        ],
        correctAnswer:
          "NHL - Stanley Cup, NFL - Lombardi Trophy, NBA - Larry O'Brien Trophy, MLB - Commissioner's Trophy",
        points: 20,
      },
    ],
    createdAt: "2024-03-01T08:15:00Z",
    updatedAt: "2024-03-01T08:15:00Z",
  },
  {
    id: 9,
    title: "Music Theory Fundamentals",
    description: "Learn and test your understanding of basic music theory concepts",
    creatorId: 789,
    status: EStatus.DRAFT,
    category: ECategory.MUSIC,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 70,
      shuffleQuestions: false,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "How many notes are in a major scale?",
        type: "multiple-choice",
        options: ["7", "8", "12", "5"],
        correctAnswer: "7",
        points: 10,
      },
      {
        id: 2,
        text: "A sharp symbol raises a note by one semitone.",
        type: "true-false",
        correctAnswer: true,
        points: 5,
      },
      {
        id: 3,
        text: "Listen to this audio clip and identify the instrument.",
        type: "audio-based",
        src: "https://freepik-tunes.s3.amazonaws.com/tracks/cc1926f1_Twilight_Transit.mp3",
        options: ["Piano", "Guitar", "Violin", "Flute"],
        correctAnswer: "Piano",
        points: 15,
      },
      {
        id: 4,
        text: "A time signature of 4/4 means there are ___ beats per measure.",
        type: "fill-in-the-blank",
        correctAnswer: "4",
        points: 10,
      },
    ],
    createdAt: "2024-02-28T15:45:00Z",
    updatedAt: "2024-02-28T15:45:00Z",
  },
  {
    id: 10,
    title: "Culinary Arts & Food History",
    description: "Explore the world of food, cooking techniques, and culinary traditions",
    creatorId: 123,
    status: EStatus.ARCHIVED,
    category: ECategory.FOOD_AND_DRINK,
    difficulty: EDifficulty.EASY,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 45,
      passingScorePercentage: 60,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 4,
    },
    questions: [
      {
        id: 1,
        text: "What is the main ingredient in guacamole?",
        type: "multiple-choice",
        options: ["Avocado", "Tomato", "Pepper", "Onion"],
        correctAnswer: "Avocado",
        points: 5,
      },
      {
        id: 2,
        text: "Sushi originated in Japan.",
        type: "true-false",
        correctAnswer: true,
        points: 5,
      },
      {
        id: 3,
        text: "Match the dishes with their countries of origin.",
        type: "matching",
        leftOptions: ["Paella", "Pho", "Tacos", "Pasta"],
        rightOptions: ["Spain", "Vietnam", "Mexico", "Italy"],
        correctAnswer: "Paella - Spain, Pho - Vietnam, Tacos - Mexico, Pasta - Italy",
        points: 20,
      },
      {
        id: 4,
        text: "What cooking method involves submerging food in hot oil?",
        type: "short-answer",
        correctAnswer: "deep frying",
        points: 10,
      },
    ],
    createdAt: "2023-11-20T12:00:00Z",
    updatedAt: "2024-01-05T10:00:00Z",
  },
  {
    id: 11,
    title: "Video Game Legends",
    description: "Test your knowledge of iconic games, characters, and gaming history",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.VIDEO_GAMES,
    difficulty: EDifficulty.HARD,
    gameMode: EGameMode.TIMED,
    settings: {
      timeLimitPerRound: 35,
      passingScorePercentage: 75,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What year was the first Legend of Zelda game released?",
        type: "multiple-choice",
        options: ["1986", "1985", "1987", "1984"],
        correctAnswer: "1986",
        points: 15,
      },
      {
        id: 2,
        text: "Watch this video clip and identify the game.",
        type: "video-based",
        options: ["Dark Souls", "Elden Ring", "Bloodborne", "Sekiro"],
        correctAnswer: "Dark Souls",
        points: 20,
        doublePoints: true,
      },
      {
        id: 3,
        text: "Arrange these gaming consoles in order of release.",
        type: "ordering",
        options: ["Nintendo Entertainment System", "PlayStation", "Xbox", "Nintendo Switch"],
        correctAnswer: "Nintendo Entertainment System, PlayStation, Xbox, Nintendo Switch",
        points: 25,
      },
      {
        id: 4,
        text: "The protagonist of Half-Life is named Gordon ___.",
        type: "fill-in-the-blank",
        correctAnswer: "Freeman",
        points: 15,
      },
      {
        id: 5,
        text: "Mario first appeared in Donkey Kong.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 6,
        text: "Match the game series with their developers.",
        type: "matching",
        leftOptions: ["The Witcher", "Halo", "God of War", "Uncharted"],
        rightOptions: ["CD Projekt Red", "Bungie", "Santa Monica Studio", "Naughty Dog"],
        correctAnswer:
          "The Witcher - CD Projekt Red, Halo - Bungie, God of War - Santa Monica Studio, Uncharted - Naughty Dog",
        points: 30,
      },
    ],
    createdAt: "2024-03-02T17:20:00Z",
    updatedAt: "2024-03-02T17:20:00Z",
  },
  {
    id: 12,
    title: "Entertainment & Pop Culture",
    description:
      "Test your knowledge of celebrity gossip, red carpet events, and entertainment scandals",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.ENTERTAINMENT,
    difficulty: EDifficulty.EASY,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 60,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 4,
    },
    questions: [
      {
        id: 1,
        text: "Which actress won Best Actress at the 2024 Oscars?",
        type: "multiple-choice",
        options: ["Emma Stone", "Margot Robbie", "Cate Blanchett", "Saoirse Ronan"],
        correctAnswer: "Emma Stone",
        points: 10,
      },
      {
        id: 2,
        text: "Taylor Swift is a singer and actress.",
        type: "true-false",
        correctAnswer: true,
        points: 5,
      },
      {
        id: 3,
        text: "Who is known as the 'King of Pop'?",
        type: "short-answer",
        correctAnswer: "Michael Jackson",
        points: 15,
      },
      {
        id: 4,
        text: "Match the celebrity with their profession.",
        type: "matching",
        leftOptions: ["Dwayne Johnson", "The Weeknd", "Elon Musk", "Oprah Winfrey"],
        rightOptions: ["Actor", "Singer", "Entrepreneur", "Talk Show Host"],
        correctAnswer:
          "Dwayne Johnson - Actor, The Weeknd - Singer, Elon Musk - Entrepreneur, Oprah Winfrey - Talk Show Host",
        points: 20,
      },
    ],
    createdAt: "2024-03-03T09:30:00Z",
    updatedAt: "2024-03-03T09:30:00Z",
  },
  {
    id: 13,
    title: "Classic Literature",
    description: "Explore the timeless works of great authors",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.LITERATURE,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 60,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "Who wrote 'Pride and Prejudice'?",
        type: "multiple-choice",
        options: ["Jane Austen", "Charlotte Brontë", "Emily Dickinson", "Mary Shelley"],
        correctAnswer: "Jane Austen",
        points: 15,
      },
      {
        id: 2,
        text: "'Moby Dick' is a novel about a whale.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the title of Fyodor Dostoevsky's most famous work?",
        type: "short-answer",
        correctAnswer: "Crime and Punishment",
        points: 15,
      },
      {
        id: 4,
        text: "Match the books with their authors.",
        type: "matching",
        leftOptions: ["1984", "The Great Gatsby", "Jane Eyre", "Wuthering Heights"],
        rightOptions: ["George Orwell", "F. Scott Fitzgerald", "Charlotte Brontë", "Emily Brontë"],
        correctAnswer:
          "1984 - George Orwell, The Great Gatsby - F. Scott Fitzgerald, Jane Eyre - Charlotte Brontë, Wuthering Heights - Emily Brontë",
        points: 25,
      },
      {
        id: 5,
        text: "Arrange these literary genres from oldest to newest.",
        type: "ordering",
        options: ["Epic Poetry", "Modernism", "Romanticism", "Contemporary Fiction"],
        correctAnswer: "Epic Poetry, Romanticism, Modernism, Contemporary Fiction",
        points: 20,
      },
    ],
    createdAt: "2024-03-03T11:20:00Z",
    updatedAt: "2024-03-03T11:20:00Z",
  },
  {
    id: 14,
    title: "Visual Arts & Design",
    description: "Discover the world of painting, sculpture, and art history",
    creatorId: 123,
    status: EStatus.PUBLISHED,
    category: ECategory.ART,
    difficulty: EDifficulty.HARD,
    gameMode: EGameMode.TIMED,
    settings: {
      timeLimitPerRound: 45,
      passingScorePercentage: 75,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "Who painted the Mona Lisa?",
        type: "multiple-choice",
        options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"],
        correctAnswer: "Leonardo da Vinci",
        points: 10,
      },
      {
        id: 2,
        text: "Identify the artwork in the image.",
        type: "image-based",
        src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/1280px-1665_Girl_with_a_Pearl_Earring.jpg",
        options: [
          "The Starry Night",
          "The Persistence of Memory",
          "A Sunday on La Grande Jatte",
          "Girl with a Pearl Earring",
        ],
        correctAnswer: "The Starry Night",
        points: 20,
        doublePoints: true,
      },
      {
        id: 3,
        text: "The technique of using small dots of paint to create images is called ___.",
        type: "fill-in-the-blank",
        correctAnswer: "pointillism",
        points: 15,
      },
      {
        id: 4,
        text: "Match the artists with their art movements.",
        type: "matching",
        leftOptions: ["Vincent van Gogh", "Pablo Picasso", "Jackson Pollock", "Andy Warhol"],
        rightOptions: ["Post-Impressionism", "Cubism", "Abstract Expressionism", "Pop Art"],
        correctAnswer:
          "Vincent van Gogh - Post-Impressionism, Pablo Picasso - Cubism, Jackson Pollock - Abstract Expressionism, Andy Warhol - Pop Art",
        points: 25,
      },
    ],
    createdAt: "2024-03-03T13:40:00Z",
    updatedAt: "2024-03-03T13:40:00Z",
  },
  {
    id: 15,
    title: "TV Shows Through the Ages",
    description: "Test your knowledge of iconic television programs",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.TV_SHOWS,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 55,
      passingScorePercentage: 65,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "How many seasons did Breaking Bad have?",
        type: "multiple-choice",
        options: ["5", "6", "7", "8"],
        correctAnswer: "5",
        points: 15,
      },
      {
        id: 2,
        text: "Game of Thrones is based on a book series.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the name of the coffee shop in Friends?",
        type: "short-answer",
        correctAnswer: "Central Perk",
        points: 15,
      },
      {
        id: 4,
        text: "Arrange these TV series by their premiere year.",
        type: "ordering",
        options: ["The Office", "Stranger Things", "The Crown", "Succession"],
        correctAnswer: "The Office, The Crown, Stranger Things, Succession",
        points: 20,
      },
      {
        id: 5,
        text: "Match the TV show with the actor who plays the main role.",
        type: "matching",
        leftOptions: ["House", "Sherlock", "The Wire", "The Sopranos"],
        rightOptions: ["Hugh Laurie", "Benedict Cumberbatch", "Dominic West", "James Gandolfini"],
        correctAnswer:
          "House - Hugh Laurie, Sherlock - Benedict Cumberbatch, The Wire - Dominic West, The Sopranos - James Gandolfini",
        points: 25,
      },
    ],
    createdAt: "2024-03-03T15:10:00Z",
    updatedAt: "2024-03-03T15:10:00Z",
  },
  {
    id: 16,
    title: "The Animal Kingdom",
    description: "Test your knowledge of wildlife, animal behavior, and zoology",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.ANIMALS,
    difficulty: EDifficulty.EASY,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 60,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 4,
    },
    questions: [
      {
        id: 1,
        text: "What is the fastest land animal?",
        type: "multiple-choice",
        options: ["Cheetah", "Lion", "Antelope", "Horse"],
        correctAnswer: "Cheetah",
        points: 10,
      },
      {
        id: 2,
        text: "Dolphins are fish.",
        type: "true-false",
        correctAnswer: false,
        points: 5,
      },
      {
        id: 3,
        text: "How many legs does an insect have?",
        type: "short-answer",
        correctAnswer: "6",
        points: 10,
      },
      {
        id: 4,
        text: "Match the animals with their diets.",
        type: "matching",
        leftOptions: ["Lion", "Cow", "Bear", "Parrot"],
        rightOptions: ["Carnivore", "Herbivore", "Omnivore", "Frugivore"],
        correctAnswer: "Lion - Carnivore, Cow - Herbivore, Bear - Omnivore, Parrot - Frugivore",
        points: 20,
      },
      {
        id: 5,
        text: "Identify the animal in the image.",
        type: "image-based",
        src: "https://www.wwf.de/fileadmin/_processed_/b/c/csm_jaguar-WW1108826-c-Yves-Jacques-REY-MILLET-WWF_a50dfac362.jpg",
        options: ["Tiger", "Leopard", "Jaguar", "Cheetah"],
        correctAnswer: "Tiger",
        points: 15,
      },
    ],
    createdAt: "2024-03-04T08:50:00Z",
    updatedAt: "2024-03-04T08:50:00Z",
  },
  {
    id: 17,
    title: "Nature & Environmental Science",
    description: "Explore ecosystems, climate, and environmental conservation",
    creatorId: 123,
    status: EStatus.PUBLISHED,
    category: ECategory.NATURE,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 55,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "What is the largest rainforest in the world?",
        type: "multiple-choice",
        options: [
          "Amazon Rainforest",
          "Congo Rainforest",
          "Southeast Asian Rainforest",
          "Daintree Rainforest",
        ],
        correctAnswer: "Amazon Rainforest",
        points: 15,
      },
      {
        id: 2,
        text: "Climate change is primarily caused by greenhouse gases.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the process by which plants convert sunlight into chemical energy?",
        type: "short-answer",
        correctAnswer: "photosynthesis",
        points: 15,
      },
      {
        id: 4,
        text: "Match the biomes with their characteristics.",
        type: "matching",
        leftOptions: ["Desert", "Tundra", "Tropical", "Temperate"],
        rightOptions: ["Hot and dry", "Cold and frozen", "Hot and humid", "Moderate climate"],
        correctAnswer:
          "Desert - Hot and dry, Tundra - Cold and frozen, Tropical - Hot and humid, Temperate - Moderate climate",
        points: 20,
      },
      {
        id: 5,
        text: "Arrange these conservation efforts from most to least recent.",
        type: "ordering",
        options: [
          "Paris Climate Agreement",
          "Montreal Protocol",
          "Kyoto Protocol",
          "Rio Earth Summit",
        ],
        correctAnswer:
          "Rio Earth Summit, Montreal Protocol, Kyoto Protocol, Paris Climate Agreement",
        points: 25,
      },
    ],
    createdAt: "2024-03-04T10:25:00Z",
    updatedAt: "2024-03-04T10:25:00Z",
  },
  {
    id: 18,
    title: "Space Exploration & Astronomy",
    description: "Journey through the universe and test your cosmic knowledge",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.SPACE,
    difficulty: EDifficulty.HARD,
    gameMode: EGameMode.TIMED,
    settings: {
      timeLimitPerRound: 45,
      passingScorePercentage: 75,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What year did humans first land on the moon?",
        type: "multiple-choice",
        options: ["1969", "1970", "1972", "1968"],
        correctAnswer: "1969",
        points: 15,
      },
      {
        id: 2,
        text: "The Sun is the largest object in our solar system.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the name of the boundary around a black hole from which nothing can escape?",
        type: "short-answer",
        correctAnswer: "event horizon",
        points: 20,
        doublePoints: true,
      },
      {
        id: 4,
        text: "Match the planets with their characteristics.",
        type: "matching",
        leftOptions: ["Venus", "Mars", "Jupiter", "Saturn"],
        rightOptions: ["Hottest planet", "Red planet", "Largest planet", "Ring planet"],
        correctAnswer:
          "Venus - Hottest planet, Mars - Red planet, Jupiter - Largest planet, Saturn - Ring planet",
        points: 25,
      },
      {
        id: 5,
        text: "Arrange these space missions chronologically.",
        type: "ordering",
        options: ["Apollo 11", "Voyager 1", "International Space Station", "SpaceX Falcon Heavy"],
        correctAnswer: "Apollo 11, Voyager 1, International Space Station, SpaceX Falcon Heavy",
        points: 25,
      },
    ],
    createdAt: "2024-03-04T12:30:00Z",
    updatedAt: "2024-03-04T12:30:00Z",
  },
  {
    id: 19,
    title: "Mathematics Mastery",
    description: "Challenge yourself with mathematical problems and concepts",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.MATH,
    difficulty: EDifficulty.EXPERT,
    gameMode: EGameMode.SURVIVAL,
    settings: {
      timeLimitPerRound: 90,
      passingScorePercentage: 85,
      shuffleQuestions: false,
      immediateResults: true,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What is the value of pi rounded to two decimal places?",
        type: "multiple-choice",
        options: ["3.14", "3.15", "3.16", "3.17"],
        correctAnswer: "3.14",
        points: 10,
      },
      {
        id: 2,
        text: "The square root of 144 is 12.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the sum of angles in a triangle?",
        type: "short-answer",
        correctAnswer: "180",
        points: 15,
      },
      {
        id: 4,
        text: "What is the value of 2^8?",
        type: "fill-in-the-blank",
        correctAnswer: "256",
        points: 20,
        doublePoints: true,
      },
      {
        id: 5,
        text: "Match the mathematical concepts with their definitions.",
        type: "matching",
        leftOptions: ["Prime Number", "Composite Number", "Perfect Square", "Integer"],
        rightOptions: [
          "Divisible only by 1 and itself",
          "Has more than two factors",
          "Result of multiplying a number by itself",
          "Whole number",
        ],
        correctAnswer:
          "Prime Number - Divisible only by 1 and itself, Composite Number - Has more than two factors, Perfect Square - Result of multiplying a number by itself, Integer - Whole number",
        points: 30,
      },
    ],
    createdAt: "2024-03-04T14:45:00Z",
    updatedAt: "2024-03-04T14:45:00Z",
  },
  {
    id: 20,
    title: "Language & Linguistics",
    description: "Explore languages, grammar, and communication across cultures",
    creatorId: 123,
    status: EStatus.PUBLISHED,
    category: ECategory.LANGUAGE,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "How many official languages are there in the United Nations?",
        type: "multiple-choice",
        options: ["6", "7", "5", "8"],
        correctAnswer: "6",
        points: 15,
      },
      {
        id: 2,
        text: "Mandarin Chinese is the most spoken language in the world by native speakers.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the term for a word that has the same spelling and pronunciation as another but different meaning?",
        type: "short-answer",
        correctAnswer: "homonym",
        points: 15,
      },
      {
        id: 4,
        text: "Match the languages with their countries.",
        type: "matching",
        leftOptions: ["Portuguese", "Swahili", "Thai", "Polish"],
        rightOptions: ["Brazil", "Kenya", "Thailand", "Poland"],
        correctAnswer: "Portuguese - Brazil, Swahili - Kenya, Thai - Thailand, Polish - Poland",
        points: 20,
      },
      {
        id: 5,
        text: "Arrange these languages from oldest to newest in written form.",
        type: "ordering",
        options: ["Greek", "Arabic", "English", "Mandarin"],
        correctAnswer: "Mandarin, Greek, Arabic, English",
        points: 20,
      },
    ],
    createdAt: "2024-03-04T16:15:00Z",
    updatedAt: "2024-03-04T16:15:00Z",
  },
  {
    id: 21,
    title: "Miscellaneous Trivia",
    description: "A mix of random facts from various topics and fields",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.MISCELLANEOUS,
    difficulty: EDifficulty.EASY,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 40,
      passingScorePercentage: 60,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 4,
    },
    questions: [
      {
        id: 1,
        text: "What is the capital of Australia?",
        type: "multiple-choice",
        options: ["Canberra", "Sydney", "Melbourne", "Brisbane"],
        correctAnswer: "Canberra",
        points: 10,
      },
      {
        id: 2,
        text: "The Great Wall of China is visible from space.",
        type: "true-false",
        correctAnswer: false,
        points: 5,
      },
      {
        id: 3,
        text: "How many days are in a leap year?",
        type: "short-answer",
        correctAnswer: "366",
        points: 10,
      },
      {
        id: 4,
        text: "Match the landmarks with their locations.",
        type: "matching",
        leftOptions: ["Statue of Liberty", "Big Ben", "Taj Mahal", "Machu Picchu"],
        rightOptions: ["New York", "London", "India", "Peru"],
        correctAnswer:
          "Statue of Liberty - New York, Big Ben - London, Taj Mahal - India, Machu Picchu - Peru",
        points: 20,
      },
    ],
    createdAt: "2024-03-04T18:00:00Z",
    updatedAt: "2024-03-04T18:00:00Z",
  },
  {
    id: 22,
    title: "General Knowledge Intermediate",
    description: "More challenging general knowledge questions",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.GENERAL,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.TIMED,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "What is the smallest country in the world by area?",
        type: "multiple-choice",
        options: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"],
        correctAnswer: "Vatican City",
        points: 15,
      },
      {
        id: 2,
        text: "The Amazon River is the longest river in the world.",
        type: "true-false",
        correctAnswer: false,
        points: 10,
      },
      {
        id: 3,
        text: "What year did the Titanic sink?",
        type: "short-answer",
        correctAnswer: "1912",
        points: 15,
      },
      {
        id: 4,
        text: "Match the inventions with their inventors.",
        type: "matching",
        leftOptions: ["Light Bulb", "Telephone", "Airplane", "Printing Press"],
        rightOptions: [
          "Thomas Edison",
          "Alexander Graham Bell",
          "Wright Brothers",
          "Johannes Gutenberg",
        ],
        correctAnswer:
          "Light Bulb - Thomas Edison, Telephone - Alexander Graham Bell, Airplane - Wright Brothers, Printing Press - Johannes Gutenberg",
        points: 20,
      },
      {
        id: 5,
        text: "Arrange these historical periods in chronological order.",
        type: "ordering",
        options: ["Middle Ages", "Renaissance", "Industrial Revolution", "Information Age"],
        correctAnswer: "Middle Ages, Renaissance, Industrial Revolution, Information Age",
        points: 20,
      },
    ],
    createdAt: "2024-03-04T19:30:00Z",
    updatedAt: "2024-03-04T19:30:00Z",
  },
  {
    id: 23,
    title: "Advanced Science Topics",
    description: "Deep dive into physics, chemistry, and biology",
    creatorId: 123,
    status: EStatus.PUBLISHED,
    category: ECategory.SCIENCE,
    difficulty: EDifficulty.HARD,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 70,
      passingScorePercentage: 75,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What is the most abundant element in the human body?",
        type: "multiple-choice",
        options: ["Oxygen", "Carbon", "Hydrogen", "Nitrogen"],
        correctAnswer: "Oxygen",
        points: 15,
      },
      {
        id: 2,
        text: "Photosynthesis produces oxygen and glucose from water and carbon dioxide.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the name of the protein that carries oxygen in the blood?",
        type: "short-answer",
        correctAnswer: "hemoglobin",
        points: 15,
      },
      {
        id: 4,
        text: "Match the branches of science with their focus.",
        type: "matching",
        leftOptions: ["Physics", "Chemistry", "Biology", "Geology"],
        rightOptions: [
          "Study of matter and energy",
          "Study of atoms and molecules",
          "Study of living organisms",
          "Study of rocks and Earth",
        ],
        correctAnswer:
          "Physics - Study of matter and energy, Chemistry - Study of atoms and molecules, Biology - Study of living organisms, Geology - Study of rocks and Earth",
        points: 25,
      },
      {
        id: 5,
        text: "Arrange these scientific discoveries by year.",
        type: "ordering",
        options: ["DNA Structure", "Penicillin Discovery", "Newton's Laws", "Theory of Evolution"],
        correctAnswer: "Newton's Laws, Theory of Evolution, Penicillin Discovery, DNA Structure",
        points: 25,
        doublePoints: true,
      },
    ],
    createdAt: "2024-03-04T20:50:00Z",
    updatedAt: "2024-03-04T20:50:00Z",
  },
  {
    id: 24,
    title: "Modern History Events",
    description: "Test your knowledge of 20th and 21st century historical events",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.HISTORY,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 55,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "In what year did the Berlin Wall fall?",
        type: "multiple-choice",
        options: ["1989", "1988", "1990", "1987"],
        correctAnswer: "1989",
        points: 15,
      },
      {
        id: 2,
        text: "The Cold War was a military conflict between the US and USSR.",
        type: "true-false",
        correctAnswer: false,
        points: 10,
      },
      {
        id: 3,
        text: "Who was the first President of the African National Congress after apartheid?",
        type: "short-answer",
        correctAnswer: "Nelson Mandela",
        points: 15,
      },
      {
        id: 4,
        text: "Match the historical events with their years.",
        type: "matching",
        leftOptions: ["Moon Landing", "Fall of Berlin Wall", "9/11 Attacks", "End of Cold War"],
        rightOptions: ["1969", "1989", "2001", "1991"],
        correctAnswer:
          "Moon Landing - 1969, Fall of Berlin Wall - 1989, 9/11 Attacks - 2001, End of Cold War - 1991",
        points: 25,
      },
      {
        id: 5,
        text: "Arrange these Cold War events chronologically.",
        type: "ordering",
        options: ["Cuban Missile Crisis", "Vietnam War", "Korean War", "Operation Desert Storm"],
        correctAnswer: "Korean War, Cuban Missile Crisis, Vietnam War, Operation Desert Storm",
        points: 20,
      },
    ],
    createdAt: "2024-03-04T22:10:00Z",
    updatedAt: "2024-03-04T22:10:00Z",
  },
  {
    id: 25,
    title: "Olympic Sports & Athletes",
    description: "Test your knowledge of Olympic sports and legendary athletes",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.SPORTS,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 65,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "In which year were the first modern Olympic Games held?",
        type: "multiple-choice",
        options: ["1896", "1900", "1904", "1908"],
        correctAnswer: "1896",
        points: 15,
      },
      {
        id: 2,
        text: "Ice Hockey is an Olympic sport.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "How many Olympic rings are there?",
        type: "short-answer",
        correctAnswer: "5",
        points: 10,
      },
      {
        id: 4,
        text: "Match the Olympic athletes with their sports.",
        type: "matching",
        leftOptions: ["Serena Williams", "Usain Bolt", "Nadia Comaneci", "Mark Spitz"],
        rightOptions: ["Tennis", "Track and Field", "Gymnastics", "Swimming"],
        correctAnswer:
          "Serena Williams - Tennis, Usain Bolt - Track and Field, Nadia Comaneci - Gymnastics, Mark Spitz - Swimming",
        points: 20,
      },
      {
        id: 5,
        text: "Arrange these Olympic host cities by year.",
        type: "ordering",
        options: ["Tokyo", "London", "Beijing", "Sydney"],
        correctAnswer: "Sydney, Beijing, London, Tokyo",
        points: 20,
      },
    ],
    createdAt: "2024-03-04T23:35:00Z",
    updatedAt: "2024-03-04T23:35:00Z",
  },
  {
    id: 26,
    title: "World Capitals Challenge",
    description: "Can you identify the capitals of countries around the world?",
    creatorId: 123,
    status: EStatus.PUBLISHED,
    category: ECategory.GEOGRAPHY,
    difficulty: EDifficulty.HARD,
    gameMode: EGameMode.TIMED,
    settings: {
      timeLimitPerRound: 40,
      passingScorePercentage: 75,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What is the capital of New Zealand?",
        type: "multiple-choice",
        options: ["Wellington", "Auckland", "Christchurch", "Dunedin"],
        correctAnswer: "Wellington",
        points: 15,
      },
      {
        id: 2,
        text: "Budapest is the capital of Hungary.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What is the capital of Canada?",
        type: "short-answer",
        correctAnswer: "Ottawa",
        points: 15,
      },
      {
        id: 4,
        text: "Match the countries with their capitals.",
        type: "matching",
        leftOptions: ["Thailand", "South Korea", "Indonesia", "Malaysia"],
        rightOptions: ["Bangkok", "Seoul", "Jakarta", "Kuala Lumpur"],
        correctAnswer:
          "Thailand - Bangkok, South Korea - Seoul, Indonesia - Jakarta, Malaysia - Kuala Lumpur",
        points: 25,
        doublePoints: true,
      },
      {
        id: 5,
        text: "Arrange these European capitals from north to south.",
        type: "ordering",
        options: ["Rome", "Stockholm", "Athens", "Dublin"],
        correctAnswer: "Stockholm, Dublin, Rome, Athens",
        points: 20,
      },
    ],
    createdAt: "2024-03-05T01:00:00Z",
    updatedAt: "2024-03-05T01:00:00Z",
  },
  {
    id: 27,
    title: "Grammy Awards & Music History",
    description: "Explore the world of music awards and legendary artists",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.MUSIC,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "Who has won the most Grammy Awards?",
        type: "multiple-choice",
        options: ["Beyoncé", "Taylor Swift", "Quincy Jones", "Georg Solti"],
        correctAnswer: "Beyoncé",
        points: 15,
      },
      {
        id: 2,
        text: "The Beatles broke up in 1970.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "Which musician is known as the 'Queen of Soul'?",
        type: "short-answer",
        correctAnswer: "Aretha Franklin",
        points: 15,
      },
      {
        id: 4,
        text: "Match the artists with their iconic albums.",
        type: "matching",
        leftOptions: ["The Beatles", "Pink Floyd", "David Bowie", "Prince"],
        rightOptions: ["Abbey Road", "The Dark Side of the Moon", "Ziggy Stardust", "Purple Rain"],
        correctAnswer:
          "The Beatles - Abbey Road, Pink Floyd - The Dark Side of the Moon, David Bowie - Ziggy Stardust, Prince - Purple Rain",
        points: 25,
      },
      {
        id: 5,
        text: "Arrange these music genres by when they originated.",
        type: "ordering",
        options: ["Rock", "Hip-Hop", "Jazz", "Electronic"],
        correctAnswer: "Jazz, Rock, Hip-Hop, Electronic",
        points: 20,
      },
    ],
    createdAt: "2024-03-05T02:25:00Z",
    updatedAt: "2024-03-05T02:25:00Z",
  },
  {
    id: 28,
    title: "Blockbuster Movie Quotes",
    description: "How well do you remember famous movie quotes and scenes?",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.MOVIES,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 60,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "Complete the quote: 'May the ___ be with you.'",
        type: "fill-in-the-blank",
        correctAnswer: "Force",
        points: 15,
      },
      {
        id: 2,
        text: "'I'll be back' is a famous line from The Terminator.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "Who said 'I'm Batman'?",
        type: "short-answer",
        correctAnswer: "Batman",
        points: 15,
      },
      {
        id: 4,
        text: "Match the famous movie quotes with the films they're from.",
        type: "matching",
        leftOptions: [
          "'You can't handle the truth!'",
          "'Here's looking at you, kid.'",
          "'Frankly, my dear, I don't give a damn.'",
          "'I feel the need... the need for speed!'",
        ],
        rightOptions: ["A Few Good Men", "Casablanca", "Gone with the Wind", "Top Gun"],
        correctAnswer:
          "'You can't handle the truth!' - A Few Good Men, 'Here's looking at you, kid.' - Casablanca, 'Frankly, my dear, I don't give a damn.' - Gone with the Wind, 'I feel the need... the need for speed!' - Top Gun",
        points: 25,
      },
      {
        id: 5,
        text: "Arrange these iconic films by their release year.",
        type: "ordering",
        options: ["Jaws", "E.T.", "Back to the Future", "Jurassic Park"],
        correctAnswer: "Jaws, E.T., Back to the Future, Jurassic Park",
        points: 20,
      },
    ],
    createdAt: "2024-03-05T03:50:00Z",
    updatedAt: "2024-03-05T03:50:00Z",
  },
  {
    id: 29,
    title: "Tech Industry & Innovation",
    description: "Test your knowledge of technology companies and digital innovations",
    creatorId: 123,
    status: EStatus.PUBLISHED,
    category: ECategory.TECHNOLOGY,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 55,
      passingScorePercentage: 70,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "Who is the founder of Microsoft?",
        type: "multiple-choice",
        options: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Larry Page"],
        correctAnswer: "Bill Gates",
        points: 15,
      },
      {
        id: 2,
        text: "The first iPhone was released in 2007.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What does AI stand for?",
        type: "short-answer",
        correctAnswer: "Artificial Intelligence",
        points: 10,
      },
      {
        id: 4,
        text: "Match the tech companies with their founders.",
        type: "matching",
        leftOptions: ["Apple", "Facebook", "Amazon", "Tesla"],
        rightOptions: ["Steve Jobs", "Mark Zuckerberg", "Jeff Bezos", "Elon Musk"],
        correctAnswer:
          "Apple - Steve Jobs, Facebook - Mark Zuckerberg, Amazon - Jeff Bezos, Tesla - Elon Musk",
        points: 25,
      },
      {
        id: 5,
        text: "Arrange these technological innovations chronologically.",
        type: "ordering",
        options: ["The Internet", "Personal Computers", "Smartphones", "Cloud Computing"],
        correctAnswer: "Personal Computers, The Internet, Smartphones, Cloud Computing",
        points: 20,
      },
    ],
    createdAt: "2024-03-05T05:15:00Z",
    updatedAt: "2024-03-05T05:15:00Z",
  },
  {
    id: 30,
    title: "International Cuisine",
    description: "Explore flavors and dishes from around the world",
    creatorId: 456,
    status: EStatus.PUBLISHED,
    category: ECategory.FOOD_AND_DRINK,
    difficulty: EDifficulty.MEDIUM,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 50,
      passingScorePercentage: 65,
      shuffleQuestions: true,
      immediateResults: true,
      lives: 3,
    },
    questions: [
      {
        id: 1,
        text: "What is the national dish of India?",
        type: "multiple-choice",
        options: ["Butter Chicken", "Tikka Masala", "Samosa", "Tandoori Chicken"],
        correctAnswer: "Butter Chicken",
        points: 15,
      },
      {
        id: 2,
        text: "Kimchi is a traditional Korean fermented vegetable dish.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What ingredient is essential to Japanese miso soup?",
        type: "short-answer",
        correctAnswer: "miso paste",
        points: 15,
      },
      {
        id: 4,
        text: "Match the cuisines with their signature dishes.",
        type: "matching",
        leftOptions: ["Italian", "Thai", "French", "Greek"],
        rightOptions: ["Pasta", "Pad Thai", "Croissant", "Moussaka"],
        correctAnswer: "Italian - Pasta, Thai - Pad Thai, French - Croissant, Greek - Moussaka",
        points: 20,
      },
      {
        id: 5,
        text: "Arrange these cooking methods from healthiest to least healthy.",
        type: "ordering",
        options: ["Grilling", "Steaming", "Deep Frying", "Baking"],
        correctAnswer: "Steaming, Grilling, Baking, Deep Frying",
        points: 20,
      },
    ],
    createdAt: "2024-03-05T06:40:00Z",
    updatedAt: "2024-03-05T06:40:00Z",
  },
  {
    id: 31,
    title: "Web Development Fundamentals",
    description: "Master HTML, CSS, JavaScript, and web development concepts",
    creatorId: 789,
    status: EStatus.PUBLISHED,
    category: ECategory.CODING,
    difficulty: EDifficulty.HARD,
    gameMode: EGameMode.CLASSIC,
    settings: {
      timeLimitPerRound: 70,
      passingScorePercentage: 75,
      shuffleQuestions: true,
      immediateResults: false,
      lives: 2,
    },
    questions: [
      {
        id: 1,
        text: "What does HTML stand for?",
        type: "multiple-choice",
        options: [
          "HyperText Markup Language",
          "High Tech Modern Language",
          "Home Tool Markup Language",
          "Hyperlinks and Text Markup Language",
        ],
        correctAnswer: "HyperText Markup Language",
        points: 10,
      },
      {
        id: 2,
        text: "CSS is used for styling web pages.",
        type: "true-false",
        correctAnswer: true,
        points: 10,
      },
      {
        id: 3,
        text: "What does an API stand for?",
        type: "short-answer",
        correctAnswer: "Application Programming Interface",
        points: 15,
      },
      {
        id: 4,
        text: "What does the following JavaScript code do? console.log('Hello');",
        type: "code-snippet",
        options: [
          "Prints 'Hello' to the console",
          "Creates a variable",
          "Defines a function",
          "Returns 'Hello'",
        ],
        correctAnswer: "Prints 'Hello' to the console",
        points: 15,
      },
      {
        id: 5,
        text: "Match the web technologies with their purposes.",
        type: "matching",
        leftOptions: ["HTML", "CSS", "JavaScript", "SQL"],
        rightOptions: ["Structure", "Styling", "Interactivity", "Database"],
        correctAnswer:
          "HTML - Structure, CSS - Styling, JavaScript - Interactivity, SQL - Database",
        points: 25,
        doublePoints: true,
      },
    ],
    createdAt: "2024-03-05T08:05:00Z",
    updatedAt: "2024-03-05T08:05:00Z",
  },
];
